name: CI
on:
  pull_request:
  push:
    branches [dev, master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U ruff pytest python-dotenv
      - run: ruff check .
      - run: ruff format --check .
      - run: pytest -q
